# Stage 1: Build the React app
FROM node:20-alpine AS builder
WORKDIR /app

COPY react+vite/package*.json .
RUN npm install
COPY react+vite/ .

RUN npm run build && ls -la /app

# Stage 2: Serve the React app with Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80